repos:
  - repo: local
    hooks:
      - id: jsonschema-fmt
        name: format jsonschema files
        entry: jsonschema lint 
        language: system
        files: ^ukaea-schema/.*\.schema.json

      - id: jsonschema-validate
        name: validate json schema files
        entry: jsonschema metaschema
        language: system
        files: ^ukaea-schema/.*\.schema.json
