name: Lint and Validate JSON Schemas

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - fix/**

jobs:
  lint-and-validate-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use jsonschema Action
        uses: sourcemeta/jsonschema@v11.2.0

      - name: Validate JSON Schemas
        run: jsonschema lint --strict ukaea-schema/**/*.schema.json

      - name: Verify JSON Schemas
        run: jsonschema metaschema ukaea-schema/**/*.schema.json

      - name: Report success
        if: success()
        run: echo "All JSON schemas have been successfully validated and linted!"
