name: Metadata CI Workflow
on: 
  push:
    branches: 
      - main
  pull_request: 
    branches: 
      - main


jobs: 
  validate-json: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: validate-json-files
        id: json-validate
        uses: GrantBirki/json-yaml-validate@v3
        
      # - name: checkout codes
      #   uses: actions/checkout@v2
        
      
        
      #   run: ls -R
      # - name: validate-json-file
      #   uses: cardinalby/schema-validator-action@v3
      #   with: 
      #     file: ./**/*.json
              


<<<<<<< HEAD
#job
=======
>>>>>>> parent of 29a8eb4 (fix: change json file validator package)
