name: Metadata CI Workflow
on: 
  push:
    branches: 
      - '**'
  pull_request: 
    branches: 
      - main


jobs: 
  validate-json: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v7
      - name: validate-json-files
        id: json-validate
        uses: GrantBirki/json-yaml-validate@v5
        with: 
          comment: "true"
      - name: Set up Python
        uses: actions/setup-python@v6
        with: 
          python-version: '3.11'
      - name: custom-camel-case-validation
        run: | 
          readarray -d '' json_file_paths < <(find . -name *.json -print0)
          echo ${json_file_paths[@]}
          for json_file in ${json_file_paths[@]}; do 
            python scripts/validate_camel_case.py $json_file 
          done

