name: Metadata CI Workflow
on: 
  push:
    branches: 
      - main
  pull_request: 
    branches: 
      - main


jobs: 
  validate-json: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: validate-json-files
        id: json-validate
        uses: GrantBirki/json-yaml-validate@v3
        with: 
          comment: "true"
          
      - name: Validate campaign JSON
        uses: cardinalby/schema-validator-action@v3
        with: 
          schema: ukaea-schema/facility/hive/campaign.schema.json
          file: ./ukaea-schema/examples/hive/campaign.json
      - name: Validate experiment JSON
        uses: cardinalby/schema-validator-action@v3
        with: 
          schema: ./ukaea-schema/facility/hive/campaign.schema.json 
          file: ./ukaea-schema/examples/hive/campaign.json

      # - name: Validate facility JSON
      #   uses: cardinalby/schema-validator-action@v3
      #   with: 
      #     schema: ./ukaea-schema/facility/facility.schema.json
      #     file: ./ukaea-schema/examples/facility.json
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
      - name: custom-camel-case-validation
        run: | 
          readarray -d '' json_file_paths < <(find . -name *.json -print0)
          echo ${json_file_paths[@]}
          for json_file in ${json_file_paths[@]}; do 
            python scripts/validate_camel_case.py $json_file 
          done

